import { ArticleHero, DirectAnswer, FAQSection, RelatedGuides, SourceList } from "@/components/ui";
import { buildMetadata, siteConfig } from "@/lib/site";

export const metadata = buildMetadata("WARDOGS Playtest & Closed Beta Status", "The latest official WARDOGS Closed Beta dates, access methods, and Steam Playtest status.", "/playtest");
const faq = [
  { question: "When is the WARDOGS Closed Beta?", answer: "The announced Closed Beta runs August 21–23, 2026." },
  { question: "Does pre-ordering guarantee access?", answer: "Yes. The official Steam announcement says pre-order customers receive guaranteed Closed Beta access." },
  { question: "Can I join without pre-ordering?", answer: "Possibly. A small, random number of players may be selected through the native Steam Playtest system, but access is not guaranteed." },
  { question: "Is this an open beta?", answer: "No. The announced event is described as a Closed Beta." },
];
export default function PlaytestPage(){return <article className="article-shell"><ArticleHero eyebrow="Access briefing" title="WARDOGS Playtest & Closed Beta Status" intro="The next official test window is confirmed. Access depends on pre-order status or limited Steam Playtest selection." status="Upcoming event" tone="current"/><div className="article-body"><DirectAnswer>The WARDOGS Closed Beta is scheduled for <strong>August 21–23, 2026</strong>. Pre-ordering guarantees access; a smaller number of non-preorder players may be selected via Steam Playtest.</DirectAnswer><h2>How to participate</h2><ol><li><strong>Pre-order on Steam</strong> for guaranteed Closed Beta access, according to the official announcement.</li><li><strong>Request access through Steam Playtest</strong> for a chance to be selected. This route is limited and random.</li><li><strong>Watch official Steam announcements</strong> for installation and timing instructions closer to the event.</li></ol><div className="callout"><strong>Older signup route</strong><p>The earlier external key signup was capped and is no longer presented as guaranteed access. Use the current Steam announcement as the authoritative status.</p></div><h2>What is not confirmed</h2><p>This announcement does not establish an open beta, future test dates, or console test access. Those remain separate questions until an official source confirms them.</p><h2>After the beta</h2><p>WARDOGS is scheduled to enter Steam Early Access on September 10, 2026. The beta and Early Access launch are distinct events.</p></div><SourceList sources={[{label:"Official Steam announcements",href:siteConfig.official.steamCommunity},{label:"WARDOGS on Steam",href:siteConfig.official.steam},{label:"Official community signup",href:siteConfig.official.playtest}]}/><FAQSection items={faq}/><RelatedGuides links={[{title:"Release date",href:"/release-date",text:"The Early Access timeline."},{title:"Beginner guide",href:"/beginner-guide",text:"Learn the core match systems."},{title:"Price",href:"/price",text:"Current purchase status."}]}/></article>}
